# Generated by Django 5.1.5 on 2025-01-24 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0002_gender_alter_customuser_avatar_and_more'),
        ('groups_custumer', '0003_alter_groupsclass_employe_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Спортивный разряд')),
            ],
            options={
                'verbose_name': 'Спортивный разряд',
                'verbose_name_plural': 'Спортивный разряд',
                'db_table': 'sport_category',
            },
        ),
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Ф.И.О')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9989999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contract_number', models.CharField(max_length=250, verbose_name='Номер договора')),
                ('contract_type', models.CharField(max_length=250, verbose_name='Тип договора')),
                ('strat_date', models.DateField(verbose_name='Дата начала обучения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='custumer/', verbose_name='Фото')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authen.gender', verbose_name='Пол')),
                ('groups', models.ManyToManyField(blank=True, to='groups_custumer.groupsclass', verbose_name='Группы')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('sport_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custumer.sportcategory', verbose_name='Спортивный разряд')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиент',
                'db_table': 'custumer',
            },
        ),
    ]
