# Generated by Django 5.1.5 on 2025-01-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0001_initial'),
        ('groups_custumer', '0003_alter_groupsclass_employe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRepresentatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Представители')),
            ],
            options={
                'verbose_name': 'Тип родства',
                'verbose_name_plural': 'Тип родства',
                'db_table': 'type_representatives',
            },
        ),
        migrations.CreateModel(
            name='CustumerDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('files', models.FileField(upload_to='custumer_files/', verbose_name='Файл')),
                ('custumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custumer.custumer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
                'db_table': 'custumer_docs',
            },
        ),
        migrations.CreateModel(
            name='CustumerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_classes', models.BigIntegerField(verbose_name='Количество занятий')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('unlimited', models.BooleanField(default=False, verbose_name='Безлимитный')),
                ('custumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custumer.custumer', verbose_name='Клиент')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups_custumer.groupsclass', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонемент',
                'db_table': 'custumer_subscription',
            },
        ),
        migrations.CreateModel(
            name='CustumerRepresentatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Ф.И.О')),
                ('phone', models.CharField(max_length=250, verbose_name='Телефон')),
                ('work', models.CharField(blank=True, max_length=250, null=True, verbose_name='Место работы')),
                ('custumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custumer.custumer', verbose_name='Клиент')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custumer.typerepresentatives', verbose_name='Тип родства')),
            ],
            options={
                'verbose_name': 'Представители',
                'verbose_name_plural': 'Представители',
                'db_table': 'custumer_representatives',
            },
        ),
    ]
