# Generated by Django 5.1.5 on 2025-01-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0002_typerepresentatives_custumerdocs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumersubscription',
            name='number_classes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Количество занятий'),
        ),
    ]
