# Generated by Django 5.1.5 on 2025-01-24 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_custumer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsclass',
            name='employe_id',
        ),
        migrations.AddField(
            model_name='groupsclass',
            name='employe_id',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Тренеры'),
        ),
    ]
