# Generated by Django 5.1.5 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_employe_user_alter_employe_owner'),
        ('groups_custumer', '0002_remove_groupsclass_employe_id_groupsclass_employe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsclass',
            name='employe_id',
            field=models.ManyToManyField(blank=True, null=True, to='employe.employe', verbose_name='Тренеры'),
        ),
    ]
