# Generated by Django 5.1.5 on 2025-01-23 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0002_gender_alter_customuser_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Ф.И.О')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9989999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('decription', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.gender', verbose_name='Пол')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employe',
            },
        ),
    ]
