# Generated by Django 5.1.5 on 2025-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('permissons', models.ManyToManyField(to='auth.permission')),
            ],
        ),
    ]
