# Generated by Django 5.1.5 on 2025-01-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_employe_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='Отправить приглашение'),
        ),
    ]
