# Generated by Django 5.1.5 on 2025-01-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_alter_employe_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='email',
        ),
    ]
